server:
  port: 8081

spring:
  application:
    name: user-service

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    preferIpAddress: true


  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka : true
    fetchRegistry: true

  logging:
    level:
      com.netflix.eureka: DEBUG
      org.springframework.cloud: DEBUG